apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-app

spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: devops

  template:
    metadata:
      labels:
        app: devops

    spec:
      containers:
        - name: devops-container
          image: 127214164288.dkr.ecr.ap-south-1.amazonaws.com/vle-5:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80