pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('vle-7') {
                    sh '''
                        eval $(minikube docker-env)
                        docker build -t myapp .
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('vle-7') {
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }
}
