pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('vle-7') {
                    sh 'docker build -t myapp .'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('vle-7') {
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }
}
